### ISSUE TITLE
LICENSE metadata missing in package.json

### ISSUE THREAD

**Issue by alexkrauss** [component/object#7]
Could you add the LICENSE property to package.json, and publish that version to npm?

Having proper license metadata helps greatly managing large projects with complex dependencies. Currently, when using, e.g., https://github.com/iandotkelly/nlf, this package shows up as a false positive, since the license cannot be automatically detected.

**Comment by stephenmathieson** [comment]
@alexkrauss will do shortly

/cc @iandotkelly

**Comment by stephenmathieson** [comment]
@alexkrauss I'll gladly merge a pr
